### ISSUE TITLE
Missing genPOI.py

### ISSUE THREAD

**Issue by chuckleb** [crosbymichael/mc-overviewer-docker#2]
I'm trying to generate POIs but can find the genpoi.py script. This may be a problem further upstream (i.e. the repo). 

Dockerfile change:
CMD ["--config=/minecraft/overviewer.cfg","--genpoi"]

Error:
This is the error that occurred:
Traceback (most recent call last):
  File "/usr/bin/overviewer.py", line 605, in <module>
    ret = main()
  File "/usr/bin/overviewer.py", line 130, in main
    g.genPOI.main()
  File "/usr/lib/python2.7/dist-packages/overviewer_core/aux_files/genPOI.py", line 511, in main
    handleEntities(rset, config, options.config, list(rset_filters), markers)
  File "/usr/lib/python2.7/dist-packages/overviewer_core/aux_files/genPOI.py", line 196, in handleEntities
    results = pool.map(parseBucketChunks, ((buck, rset, filters) for buck in buckets))
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 227, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 528, in get
    raise self._value
KeyError: 'Items'

**Comment by chuckleb** [comment]
This may be the case of old documentation. The genpoi seems to be integrated into the main overviewer, so doesn't exist as a standalone script. Working on getting the POIs working.
